from typing import List
from . import config
import pandas as pd

def is_numeric(value) -> bool:
    """
    Checks whether 'value' is a numeric input.
    """
    try:
        float(value)
        return True
    except (TypeError, ValueError):
        return False

def saturation(value: float, upper: float) -> float:
    """
    Saturate a value in a specific range [lower, upper].
    """
    saturated = value
    if saturated < -upper: saturated = -upper
    elif saturated > upper: saturated = upper
    return saturated
    
def suppress_oscillations(prev: float, succ: float, eps: float) -> float:
    """
    If the current value is quite the same as the previous one, this function make it exactly as the previous one.
    """
    if abs(succ-prev) < eps: succ = prev
    return succ

def apply_calibration(duties: List[int]) -> None:
    for i in range(4):
        duties[i] = int(duties[i]*config.MOTOR_CALIBRATION_FACTORS[i])

def get_time_format(elapsed_time: float) -> str:
    hours = int(elapsed_time // 3600)
    minutes = int(elapsed_time // 60)
    seconds = elapsed_time % 60
    return f"{hours}:{minutes}:{seconds:5.2f}"

def post_processing(input_csv):
    """
    Post-process the CSV data generated by the Controller class
    and save it as an ordered Excel file.
    """

    # Read the CSV file
    df = pd.read_csv(input_csv)

    # Convert 'Elapsed time (s)' to seconds if it's a string
    if df['Elapsed time (s)'].dtype == 'object':
        df['Elapsed time (s)'] = pd.to_timedelta(df['Elapsed time (s)']).dt.total_seconds()

    # Select and order the relevant columns
    ordered_columns = ['Elapsed time (s)', 'Distance (cm)', 'Speed (cm/s)', 'Duty (PWM)']
    table = df[ordered_columns]

    # Save to Excel
    output_file = input_csv.replace('.csv', '_postprocessed.xlsx')
    table.to_excel(output_file, index=False)

    print(f"Post-processed data saved to: {output_file}")

    # Print a preview of the first 10 rows
    print("\n=== DATA PREVIEW ===")
    print(table.head(10))

__all__ = ["is_numeric", "saturation", 
           "suppress_oscillations", 
           "apply_calibration",
           "get_time_format",
           "post_processing"]