from typing import List
import config
import pandas as pd

def is_numeric(value) -> bool:
    """
    Checks whether 'value' is a numeric input.
    """
    try:
        float(value)
        return True
    except (TypeError, ValueError):
        return False

def saturation(value: float, upper: float) -> float:
    """
    Saturate a value in a specific range [lower, upper].
    """
    saturated = value
    if saturated < -upper: saturated = -upper
    elif saturated > upper: saturated = upper
    return saturated
    
def suppress_oscillations(prev: float, succ: float, eps: float, force: bool = False) -> float:
    """
    If the current value is quite the same as the previous one, this function make it exactly as the previous one.
    If force is True,  bypass the filter
    """
    if not force and abs(succ-prev) < eps: succ = prev
    return succ

def apply_calibration(duties: List[int]) -> None:
    for i in range(4):
        duties[i] = int(duties[i]*config.MOTOR_CALIBRATION_FACTORS[i])

def get_time_format(elapsed_time: float) -> str:
    hours = int(elapsed_time // 3600)
    minutes = int((elapsed_time % 3600) // 60)
    seconds = elapsed_time % 60
    return f"{hours:02d}:{minutes:02d}:{seconds:05.2f}"

def post_processing(input_csv):
    """
    Post-process the CSV data generated by the Controller class
    and save it as an ordered Excel file.
    """

    # Read the CSV file
    df = pd.read_csv(input_csv)

    # Normalize timestamp columns to seconds.
    # NOTE: `pd.to_timedelta` on numeric-like strings (e.g. "1.23")
    # interprets them as nanoseconds, not seconds.
    for col in ['Real elapsed time (s)', 'Elapsed time (s)']:
        if df[col].dtype == 'object':
            numeric_seconds = pd.to_numeric(df[col], errors='coerce')
            if numeric_seconds.notna().all():
                df[col] = numeric_seconds
            else:
                parsed = pd.to_timedelta(df[col], errors='coerce').dt.total_seconds()
                df[col] = numeric_seconds.fillna(parsed)

    # Select and order the relevant columns
    ordered_columns = ['Real elapsed time (s)', 'Elapsed time (s)', 'Distance (cm)', 'Speed (cm/s)', 'Duty (PWM)']
    table = df[ordered_columns]

    # Save to Excel
    output_file = input_csv.replace('.csv', '_postprocessed.xlsx')
    table.to_excel(output_file, index=False)

    print(f"Post-processed data saved to: {output_file}")

    # Print a preview
    nrows = 10
    print(f"\n=== DATA PREVIEW (first {nrows} rows) ===")
    print(table.head(10))

def speed_to_PWM(speed: float) -> int:
    """
    Obtained through Excel interpolation for a set of measurments. Computes
    the pwm input for the robot from the output given by the controller.
    """
    [a, b, c, d] = config.direct_conv_fun_coeff;
    if speed != 0: sign = int(speed / abs(speed))
    else: sign = 0
    abs_speed = abs(speed)
    abs_pwm = int(a * pow(abs_speed, 3) + b * pow(abs_speed, 2) + c * abs_speed + d)
    return sign * abs_pwm;

def dead_zone_corrector(pwm: int) -> int:
    """
    A discontinuity offset at zero models coulomb friction. 
    Linear gain models viscous friction.
    y = sign(x) * (Gain * abs(x) + Offset)
    """ 
    if pwm != 0: sign = pwm/abs(pwm)
    else: sign = 1
    # from simulink simulation
    gain = 1
    offset = config.DEAD_ZONE
    return int(sign * (gain * abs(pwm) + offset))

__all__ = ["is_numeric", "saturation",
           "suppress_oscillations",
           "apply_calibration",
           "get_time_format",
           "post_processing",
           "speed_to_PWM",
           "PWM_to_speed",
           "dead_zone_corrector"]
